version: '2.1'

orbs:
  php: circleci/php@1.1.0
  # phpunit: stockfiller/phpunit@1.0.0
  
jobs:
  install_php:
      docker:
        - image: 'cimg/base:edge'
      steps:
        - checkout
        - php/install-php:
            version: '7.4'

  install_composer_packages:
    executor: php/default
    steps:
      - checkout
      - php/install-composer:
          install-version: 1.10.16
      - php/install-packages
      - run: ./vendor/bin/phpunit

  # execute_php_unit_tests:
  #   executor: php/default
  #   steps:
  #     - checkout
workflows:
  install:
    jobs:
      - install_php
      - install_composer_packages
      # - execute_php_unit_tests 